/**
 * Vet CRM Web - Theme tokens (single source of truth).
 * Values mirror css-variables.css. Prefer Tailwind theme classes in UI
 * (bg-brand-blue, text-success, etc.) — never hardcoded palette colors.
 */
export const theme = {
  colors: {
    primary: '#EA580C',
    primaryHover: '#C2410C',
    primaryMuted: '#FFEDD5',
    brandBlue: '#0068FF',
    brandBlueHover: '#1878E6',
    background: '#F6F8FE',
    backgroundMuted: '#FEF3C7',
    foreground: '#333333',
    foregroundMuted: '#6B7280',
    border: '#E5E7EB',
    card: '#FFFFFF',
    onContrast: '#FFFFFF',
    surfaceActive: '#F5EFE6',
    surfaceBoard: '#F7F8FB',
    surfaceOnline: '#F7FAF7',
    success: '#059669',
    successHover: '#047857',
    successMuted: '#D1FAE5',
    successForeground: '#047857',
    error: '#DC2626',
    danger: '#DC2626',
    dangerHover: '#B91C1C',
    dangerMuted: '#FEF2F2',
    dangerForeground: '#B91C1C',
    caution: '#D97706',
    cautionMuted: '#FEF3C7',
    cautionForeground: '#92400E',
    info: '#0284C7',
    infoMuted: '#E0F2FE',
    infoForeground: '#0369A1',
    neutral: '#64748B',
    neutralMuted: '#F1F5F9',
    neutralForeground: '#475569',
    accent: '#7C3AED',
    accentMuted: '#F5F3FF',
    accentForeground: '#6D28D9',
    warning: '#DC2626',
    warningMuted: '#FFF0E0',
    tag: '#FEF3C7',
    emergency: '#E16868',
    emergencyHover: '#D45555',
    emergencyMuted: '#FCE8E8',
    emergencyForeground: '#B54545',
  },
  spacing: {
    /** Multiplier × 4px — matches Tailwind spacing (p-4 = 16px) */
    unit: 'var(--spacing-unit)',
    1: 'calc(var(--spacing-unit) * 1)',
    2: 'calc(var(--spacing-unit) * 2)',
    3: 'calc(var(--spacing-unit) * 3)',
    4: 'calc(var(--spacing-unit) * 4)',
    5: 'calc(var(--spacing-unit) * 5)',
    6: 'calc(var(--spacing-unit) * 6)',
    8: 'calc(var(--spacing-unit) * 8)',
    10: 'calc(var(--spacing-unit) * 10)',
    12: 'calc(var(--spacing-unit) * 12)',
    16: 'calc(var(--spacing-unit) * 16)',
    20: 'calc(var(--spacing-unit) * 20)',
    24: 'calc(var(--spacing-unit) * 24)',
  },
  borderRadius: {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
    xl: '1rem',
    full: '9999px',
  },
  fontFamily: {
    sans: 'var(--font-dm-sans), ui-sans-serif, system-ui, sans-serif',
    heading: 'var(--font-comfortaa), ui-sans-serif, system-ui, sans-serif',
    comfortaa: 'var(--font-comfortaa), sans-serif',
    dmSans: 'var(--font-dm-sans), sans-serif',
  },
  fontSize: {
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
  },
} as const;

export type Theme = typeof theme;
