import type { PetSpecies } from '@petspond/types';

/** Curated lists for dog & cat (only species with structured breeds in the app). */

export const DOG_BREEDS: string[] = [
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akita',
  'Alaskan Malamute',
  'American Bulldog',
  'American Eskimo Dog',
  'Australian Cattle Dog',
  'Australian Shepherd',
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Belgian Malinois',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Bloodhound',
  'Border Collie',
  'Border Terrier',
  'Boston Terrier',
  'Boxer',
  'Brittany',
  'Bull Terrier',
  'Bulldog (English)',
  'Bullmastiff',
  'Cairn Terrier',
  'Cane Corso',
  'Cavalier King Charles Spaniel',
  'Chesapeake Bay Retriever',
  'Chihuahua',
  'Chinese Crested',
  'Chow Chow',
  'Cockapoo',
  'Cocker Spaniel',
  'Collie',
  'Dachshund',
  'Dalmatian',
  'Doberman Pinscher',
  'Dogo Argentino',
  'Dutch Shepherd',
  'English Mastiff',
  'English Setter',
  'English Springer Spaniel',
  'French Bulldog',
  'German Shepherd',
  'German Shorthaired Pointer',
  'Golden Retriever',
  'Great Dane',
  'Great Pyrenees',
  'Greyhound',
  'Havanese',
  'Husky (Siberian)',
  'Irish Setter',
  'Irish Wolfhound',
  'Jack Russell Terrier',
  'Japanese Chin',
  'Labrador Retriever',
  'Lhasa Apso',
  'Maltese',
  'Maltese Shih Tzu',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Mixed breed',
  'Newfoundland',
  'Papillon',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Pit Bull Terrier',
  'Pointer',
  'Pomeranian',
  'Poodle (Miniature)',
  'Poodle (Standard)',
  'Poodle (Toy)',
  'Pug',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Saint Bernard',
  'Samoyed',
  'Schnauzer (Giant)',
  'Schnauzer (Standard)',
  'Shar Pei',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shih Tzu',
  'Soft Coated Wheaten Terrier',
  'Vizsla',
  'Weimaraner',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Yorkshire Terrier',
].sort((a, b) => a.localeCompare(b));

export const CAT_BREEDS: string[] = [
  'Abyssinian',
  'American Bobtail',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Bengal',
  'Birman',
  'Bombay',
  'British Longhair',
  'British Shorthair',
  'Burmese',
  'Chartreux',
  'Cornish Rex',
  'Devon Rex',
  'Egyptian Mau',
  'European Shorthair',
  'Exotic Shorthair',
  'Himalayan',
  'Japanese Bobtail',
  'Maine Coon',
  'Manx',
  'Mixed breed',
  'Norwegian Forest Cat',
  'Ocicat',
  'Oriental Shorthair',
  'Persian',
  'Ragdoll',
  'Russian Blue',
  'Scottish Fold',
  'Siamese',
  'Siberian',
  'Singapura',
  'Somali',
  'Sphynx',
  'Tonkinese',
  'Turkish Angora',
  'Turkish Van',
].sort((a, b) => a.localeCompare(b));

export function breedsForDogOrCat(species: PetSpecies): string[] {
  if (species === 'dog') return DOG_BREEDS;
  if (species === 'cat') return CAT_BREEDS;
  return [];
}
