import type { Config } from 'tailwindcss';
import { buildSpacingScale } from './src/theme/spacing';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-muted': 'var(--color-primary-muted)',
        background: 'var(--color-background)',
        'background-muted': 'var(--color-background-muted)',
        foreground: 'var(--color-foreground)',
        muted: 'var(--color-muted)',
        border: 'var(--color-border)',
        card: 'var(--color-card)',
        'on-contrast': 'var(--color-on-contrast)',
        'surface-active': 'var(--color-surface-active)',
        'surface-board': 'var(--color-surface-board)',
        'surface-online': 'var(--color-surface-online)',
        success: 'var(--color-success)',
        'success-hover': 'var(--color-success-hover)',
        'success-muted': 'var(--color-success-muted)',
        'success-foreground': 'var(--color-success-foreground)',
        warning: 'var(--color-warning)',
        'warning-muted': 'var(--color-warning-muted)',
        tag: 'var(--color-tag)',
        error: 'var(--color-error)',
        danger: 'var(--color-danger)',
        'danger-hover': 'var(--color-danger-hover)',
        'danger-muted': 'var(--color-danger-muted)',
        'danger-foreground': 'var(--color-danger-foreground)',
        'danger-border': 'var(--color-danger-border)',
        emergency: 'var(--color-emergency)',
        'emergency-hover': 'var(--color-emergency-hover)',
        'emergency-muted': 'var(--color-emergency-muted)',
        'emergency-foreground': 'var(--color-emergency-foreground)',
        caution: 'var(--color-caution)',
        'caution-muted': 'var(--color-caution-muted)',
        'caution-foreground': 'var(--color-caution-foreground)',
        info: 'var(--color-info)',
        'info-muted': 'var(--color-info-muted)',
        'info-foreground': 'var(--color-info-foreground)',
        neutral: 'var(--color-neutral)',
        'neutral-muted': 'var(--color-neutral-muted)',
        'neutral-foreground': 'var(--color-neutral-foreground)',
        accent: 'var(--color-accent)',
        'accent-muted': 'var(--color-accent-muted)',
        'accent-foreground': 'var(--color-accent-foreground)',
        'brand-blue': 'var(--color-brand-blue)',
        'brand-blue-hover': 'var(--color-brand-blue-hover)',
        'onboarding-accent': 'var(--color-onboarding-accent)',
        'input-border': 'var(--color-input-border)',
        'step-muted': 'var(--color-step-muted)',
        'sidebar-tip-bg': 'var(--color-sidebar-tip-bg)',
        'avatar-1-bg': 'var(--color-avatar-1-bg)',
        'avatar-1-fg': 'var(--color-avatar-1-fg)',
        'avatar-2-bg': 'var(--color-avatar-2-bg)',
        'avatar-2-fg': 'var(--color-avatar-2-fg)',
        'avatar-3-bg': 'var(--color-avatar-3-bg)',
        'avatar-3-fg': 'var(--color-avatar-3-fg)',
        'avatar-4-bg': 'var(--color-avatar-4-bg)',
        'avatar-4-fg': 'var(--color-avatar-4-fg)',
        'avatar-5-bg': 'var(--color-avatar-5-bg)',
        'avatar-5-fg': 'var(--color-avatar-5-fg)',
        'avatar-6-bg': 'var(--color-avatar-6-bg)',
        'avatar-6-fg': 'var(--color-avatar-6-fg)',
      },
      fontFamily: {
        sans: ['var(--font-dm-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        heading: ['var(--font-comfortaa)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['var(--font-comfortaa)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        comfortaa: ['var(--font-comfortaa)', 'sans-serif'],
        'dm-sans': ['var(--font-dm-sans)', 'sans-serif'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      fontSize: {
        '4.5xl': ['2.5rem', { lineHeight: '1.2' }], // 40px
      },
      spacing: buildSpacingScale(),
    },
  },
  plugins: [],
};

export default config;
